import "../globals.css"; // ajusta la ruta según corresponda
import ClientWrapper from "./ClientWrapper";

export const metadata = {
  title: "LinkHub",
  description: "Generated by Next.js",
};

export default function AppLayout({ children }) {
  return <ClientWrapper>{children}</ClientWrapper>;
}
