import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import AppSidebar from "@/components/layout/AppSidebar";
import { Page } from "@/models/Page";
import mongoose from "mongoose";
import { getServerSession } from "next-auth";
import { Lato } from "next/font/google";
import "../globals.css";
import { headers } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "LinkHub",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {
  const headersList = headers();
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }
  mongoose.connect(process.env.MONGO_URI);
  const page = await Page.findOne({ owner: session.user.email });

  return (
    <html lang="es">
      <body className={lato.className}>
        <Toaster />
        <main className="flex min-h-screen">
          {/* Sidebar fijo */}
          <AppSidebar />

          {children}
        </main>
      </body>
    </html>
  );
}
